### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [Tun0123/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by Tun0123** [comment]
I added the viewport metatag to the header and now the page looks better on my mobile device.

<meta name="viewport" content="width=device-width, initial-scale=1">

Cheers

**Comment by BillyMassey** [comment]
Looks good! Keep up the good work.
